version: "3.4"

services:
  app:
    image: ${IMAGE_APP}
    container_name: equipment__app
    build:
      context: ./src
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      - db

  db:
    container_name: equipment__db
    image: ${IMAGE_DB}
    build: ./postgres
    env_file:
      - .env
    volumes: [ "db_volume:/var/lib/postgresql/data/" ]
    restart: always
    ports:
      - 5432:5432

volumes:
  db_volume:
